### ISSUE TITLE
1 bug and 1 suggestion

### ISSUE THREAD

**Issue by Professidero** [cakebake/markdown-themeable-pdf#1]
Hi ! 

First of all, thank you for this cool package, it works well on the majority of my markdown files ^^

But I got a problem with one of them : it's so huge that I use some huge comments to navigate in it via the minimap. Only this kind of comments are just stopping the PDF conversion (short comments doesn't stop the conversion : `<!-- TOC depth:6 withLinks:1 updateOnSave:1 orderedList:1 -->` )
And here is an example of a file which won't be completed as PDF because of the "PREZ" comment : http://pastebin.com/kVpRWnFj

Finally, I got 1 suggestion to enhance your package : the support of local images, it would be cool :D

**Comment by cakebake** [comment]
I'm going to run some tests with your Markdown. **Thank you for providing** :)

Regarding your proposal with the local images ... I think that's definitely important!!
Currently I have a few more local branches in which I perform tests. The best result counts.

**Comment by cakebake** [comment]
Ok, block comments no longer stop the document in v0.2.0 :) [comments.markdown.pdf](/cakebake/markdown-themeable-pdf/blob/master/tests/comments.markdown.pdf)

Local images coming soon.

**Comment by Professidero** [comment]
Haha nice ! Thank you :)

**Comment by cakebake** [comment]
Supports local images by 949616acb760cadb586446c3061ece80608351d4 :)
