### ISSUE TITLE
Text is not bolded in html tags

### ISSUE THREAD

**Issue by SirKitboard** [cakebake/markdown-themeable-pdf#10]
For certain reasons i had to manually make my list items with an ol tags and discovered that text bolding doesnt work with it. For example for the mark down : 

``` html
<ol>
<li> **Hello** </li>
</ol>
```

results in the list item being surrounded by asteriks instead of bold. Might be the same issue with italics as well though i did not test that

**Comment by cakebake** [comment]
Hey SirKitboard,

Markdown inside of HTML-Tags could not be parsed. Please use either Markdown or HTML, but do not mix it.

#### Correct HTML

```
<ol>
    <li><i>One (in italic)</i></li>
    <li>Two</li>
    <li><strong>Three (in bold)</strong></li>
</ol>
```

#### Correct Markdown

```
1.  *One (in italic)*
2.  Two
3.  **Three (in bold)**
```
