### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to s...

### ISSUE THREAD

**Issue by DouglasUrner** [cakebake/markdown-themeable-pdf#106]
[Enter steps to reproduce:]

1. Install markdown-themeable-pdf on Windows 7 behind a firewall (use apm config set strict-ssl false to work around certificate problems).
2. Open a Markdown file.
3. Attempt to convert to PDF with Control-Shift-E

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

```
At assert.js:42

AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at /packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:38:3)
    at /packages/markdown-themeable-pdf/node_modules/html-pdf/lib/index.js:10:14)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:483:27
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Commands

```
     -0:48.4.0 markdown-themeable-pdf:export (div.line.cursor-line)
```

### Non-Core Packages

```
browser-plus 0.0.98 
language-markdown 0.25.1 
markdown-folding 0.3.1 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.7.3 
pdf-view 0.70.0 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.3.1 
wordcount 2.10.4 
```

**Comment by mrlay** [comment]
the same issue also happend to linux os(debian9)

**Comment by cakebake** [comment]
Sorry, but I can´t reproduce the problem. Currently I am working on version 2. For version 1, there are no more updates.
