### ISSUE TITLE
Custom CSS style sheet does not replace defaults for export

### ISSUE THREAD

**Issue by ylawayjdp** [cakebake/markdown-themeable-pdf#112]
I have a project with custom css stylesheet. I noticed that regardless of how I formatted my tables there were certain attributes that were not changeable when exporting to pdf. 

I exported the project to html to see what the problem was with the styles and found that another css style sheet is being referred to  in export but I do not know where these default styles are stored.

They are not stored in the default style.css in the .atom path.

**Comment by cakebake** [comment]
Do you mean the default styles?

Here is the file. Located in package directory.

https://github.com/cakebake/markdown-themeable-pdf/blob/master/css/document.css

**Comment by cakebake** [comment]
In version 2 I have the possibility to disable the standard design. The publication is pending.
