### ISSUE TITLE
macOS Mojave update loses Bold typeface

### ISSUE THREAD

**Issue by purplediane** [cakebake/markdown-themeable-pdf#115]
I upgraded my MacBook Pro to macOS Mojave and now when I run the markdown-to-PDF in Atom, the resultant PDF file does not show bold text where it should be. No error messages appear that I have seen.

I uploaded a few files to https://www.dropbox.com/sh/50i81tavdmtte8m/AACUITgLNlnHLyKjcU-4bvNZa?dl=0
There is a markdown file, `original-markdown.md` and 2 PDF files. One was generated before my upgrade from OSX El Capitan to Mojave, and the other after the upgrade. The markdown file has not changed. 
I have Atom 1.31.2, with all my packages up to date. I made no changes to packaging or my css files.

Please let me know if/how I can help you figure this out.

**Comment by purplediane** [comment]
I have a very old iMac that is at macOS High Sierra. I installed Atom and markdown-themable-pdf and it works correctly there.
That's a work-around that I can use for now, but would definitely prefer to have it work on my MacBook Pro in Mojave.

**Comment by cakebake** [comment]
Currently I am working on the [v2 of the package](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite). Is it possible for you to [install it in developer mode](https://github.com/cakebake/markdown-themeable-pdf/blob/rewrite/CONTRIBUTING.md)? Unfortunately, I'm currently unable to test myself with a Mac. The v2, however, is [tested for features regarding Travis](https://travis-ci.org/cakebake/markdown-themeable-pdf).

I would be interested in your results in the v2.

**Comment by cakebake** [comment]
Because of the v1, it might help you just uninstall and reinstall the package once. Just try it out. It may be that the modules have to be recompiled.

**Comment by purplediane** [comment]
Sorry to take so long to get back to you, my computer went to the mac-hospital for battery replacement. I upgraded everything (atom and some other packages), uninstalled the markdown-themable-pdf plugin, restarted Atom and re-installed markdown-themable-pdf, and unfortunately am having the same problem. It does not do bold anywhere, not even in the headers. The fonts otherwise look correct.

My Atom is now 1.32.0 version. I will try to take a look at this later this week and perhaps try the developer mode. 

I forgot to say that italic works. Go figure.

I also forgot to say how much I love this package. I use it for lots of things, but especially for handouts for my students.

**Comment by ekarpinskiMITRE** [comment]
I'm having the same problem. Anyone figured out a solution?

**Comment by purplediane** [comment]
> I'm having the same problem. Anyone figured out a solution?

I thought I might try to install the development mode and poke around a bit, but I have not had time to do that and doubt it will happen in the near future.

I am lucky that I have another very old Mac with High Sierra (too old for Mojave) and I put my markdown files into dropbox and convert them there, then bring them over. I admit this is not a good solution at all, but it is a workaround that I can use for now, though it doesn't help other people.

There are other ways to convert markdown to pdf, but none of them (that I've found) have the capability of a header/footer (among other things). There is another ATOM markdown to pdf package (maybe more than one), but it is not as good, IMO.

**Comment by carlonicora** [comment]
Hi,

Just a quick update on this. I could not install V2 (I don't know how to do it, sorry), but I have noticed that the font-weight does not work as well. Even importing fonts and setting the weight in the CSS, that is skipped during the PDF creation.

Hope this help

**Comment by andreasd** [comment]
same problem here :-/ also on os x mojave and a fresh install of atom and the plugin.

**Comment by dmitryperets** [comment]
Hi, the issue is still present... any plans to fix it? 
FYI - it looks like the issue is caused by the use of `html-pdf`. 
There was a similar problem reported for `mdpdf`: 
https://github.com/BlueHatbRit/mdpdf/issues/59

They solved it in version 2.0.0, and as can be seen in their release notes, they solved it by getting rid of `html-pdf`:
https://github.com/BlueHatbRit/mdpdf/releases/tag/2.0.0

**Comment by ghost** [comment]
Hi @cakebake, I can confirm that with v2 bold text appears correctly.

However, both generation and preview are much much slower, and more resource-heavy. I find the html headers easier to use.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
