### ISSUE TITLE
shared-object not found: libssl_conf.so

### ISSUE THREAD

**Issue by chymian** [cakebake/markdown-themeable-pdf#116]
on a debian buster/testing, running atom.io in a snap (1.32.2, rev: 206) i get this new error:

[Enter steps to reproduce:]

1. from a markdown, press ctrl-shift-e
2. worked till 2 weeks ago (~late october)

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Debian GNU/Linux
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught Error: html-pdf: Received the exit code '1'
Auto configuration failed
139984407043712:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
139984407043712:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139984407043712:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139984407043712:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

```
At /home/guenter/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:496

Error: html-pdf: Received the exit code '1'
Auto configuration failed
139984407043712:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
139984407043712:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139984407043712:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139984407043712:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

    at ChildProcess.respond (/packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:121:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -0:13.7.0 markdown-themeable-pdf:export (input.hidden-input)
```

### Non-Core Packages

```
hey-pane 1.1.2 
markdown-mindmap 0.6.1 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.15.8 
markdown-preview-plus 3.7.1 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.10.3 
mr-markdown-pdf 1.6.0 
pandoc-convert 1.1.1 
pdf-view 0.71.0 
tidy-markdown 3.0.1 
```

**Comment by iuvbio** [comment]
I have the same issue.

**Comment by chymian** [comment]
I found out, that this only happens with an existing/updated installation.
uninstalling the pkg. or starting over with an empty ~/.atom folder removes this problem but brings in new ones: footer/header do not work, pdf font's are different size, so pdfs look very different, ...

**Comment by cakebake** [comment]
I am currently working on a new version. v2 no longer uses phantomjs. There have been many problems with phantomJs in the past.
I am closing, because I am not making any changes to the first version of the package.
