### ISSUE TITLE
Issues with tables

### ISSUE THREAD

**Issue by flavz27** [cakebake/markdown-themeable-pdf#118]
The tables are not being rendered, it generates it as plain text. When using other .md to pdf generators, it works, such as markdown to pdf. Is this a known issue ? Is there a work around ?

thanks !

**Comment by cakebake** [comment]
This package uses markdown-it for md to html parsing. markdown-it converts by markdown spec. If you have an issue, please fill an issue in following repo:

https://github.com/markdown-it/markdown-it

My tables are rendering fine. I´m using markdown-themeable-pdf every day and with tables. Please check your syntax.
