### ISSUE TITLE
Feature request: configurable option to treat 'horizontal rule' as a page break 

### ISSUE THREAD

**Issue by mythofcode** [cakebake/markdown-themeable-pdf#119]
There is markdown syntax for a horizontal rule (three or more hyphen, underscore or asterisk characters on a line; see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#hr).

**Please add a boolean configuration option to allow one of these horizontal rule types (say hyphen) to be treated as a page break**.

This avoids having to use the div HTML markup to create multiple pages, and also makes makes Atom into an effective  replacement for the Marp presentation tool (https://yhatt.github.io/marp/).

**Comment by cakebake** [comment]
Hello,

I do not want to move away from the standard here. According to Spec, this is always a `<hr>`-tag. The HTML page break was a good solution so far. It does not appear visibly in any output format and can be easily inserted via Atom-Autocomplete `page-break` (you just have to start typing `p`).

https://spec.commonmark.org/0.28/#thematic-breaks
