### ISSUE TITLE
image is on two pages

### ISSUE THREAD

**Issue by sander76** [cakebake/markdown-themeable-pdf#12]
Maybe not a bug, but not a desired result either. I have a big image. This is image is stretched across two pages. Somehow it should be scaled down to fit one page ?

**Comment by cakebake** [comment]
Good idea, but I have currently no idea to solfe this for webkit print :/ Do you have any suggestions?

**Comment by sander76** [comment]
Me neither. It appears markdown-pdf doesn't have this issue..

**Comment by cakebake** [comment]
Yes, because no CSS or HTML control exists for it. I look around for an alternative solution.

**Comment by cakebake** [comment]
Now you control image width and height in markdown.

``` md
![test](image.png =100x200)
```

is interpreted as

``` html
<p><img src="image.png" alt="test" width="100" height="200"></p>
```
