### ISSUE TITLE
Uncaught Error: html-pdf: Received the exit code '3221225477'

### ISSUE THREAD

**Issue by snow212-cn** [cakebake/markdown-themeable-pdf#125]
[Enter steps to reproduce:]

1. Convert md to pdf with Ctrl+Shift+E. I encountered the error #106 #17 .Then I did what they suggested, I mean, I executed `npm install -g html-pdf` and `npm install -g phantomjs`. 
2. Retry to convert to pdf. Still I encountered this new error.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught Error: html-pdf: Received the exit code '3221225477'

```
At .atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:496

Error: html-pdf: Received the exit code '3221225477'
    at ChildProcess.respond (/packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:121:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -0:19.1.0 markdown-themeable-pdf:export (span.syntax--markup.syntax--underline.syntax--link)
```

### Non-Core Packages

```
atom-mermaid 3.3.1 
language-markdown 0.37.0 
markdown-folder 0.5.0 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.16.1 
markdown-preview-opener 0.1.1 
markdown-preview-plus 3.8.1 
markdown-preview-plus-opener 0.2.0 
markdown-scroll-sync 2.1.2 
markdown-table-formatter 2.9.2 
markdown-themeable-pdf 1.2.1 
markdown-toc 0.4.2 
markdown-writer 2.11.5 
mathjax-wrapper 0.1.0 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
selection-highlight 0.1.6 
simplified-chinese-menu 5.3.5 
Sublime-Style-Column-Selection 1.7.5 
tool-bar 1.1.11 
tool-bar-markdown-writer 0.5.0 
```

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
