### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by exgundam** [cakebake/markdown-themeable-pdf#128]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0-beta3 ia32
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at Object.getConfigFilePath (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:575:28)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:365:44
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

### Commands

```
     -5:00.8.0 markdown-themeable-pdf:export (div.line)
  2x -0:28.6.0 find-and-replace:use-selection-as-replace-pattern (input.hidden-input)
 15x -0:18.2.0 markdown-themeable-pdf:export (div.markdown-preview)
```

### Non-Core Packages

```
markdown-pdf 2.2.0 
markdown-themeable-pdf 1.2.1 
```

**Comment by jakobschumacher** [comment]
I have the same problem. Reinstalling it didnt help. I use custom header and footer in the default path

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1


### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Object.getConfigFilePath (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:575:28)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:365:44
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

### Commands

```
     -5:03.7.0 core:move-up (input.hidden-input)
     -5:02.8.0 core:confirm (input.hidden-input)
     -5:02.8.0 markdown-themeable-pdf:export (input.hidden-input)
  2x -4:11.9.0 core:backspace (input.hidden-input)
     -1:19.5.0 intentions:highlight (input.hidden-input)
     -1:18.8.0 find-and-replace:use-selection-as-replace-pattern (input.hidden-input)
     -0:54.8.0 intentions:highlight (input.hidden-input)
     -0:54.6.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
 19x -0:48.4.0 core:backspace (input.hidden-input)
     -0:47.2.0 editor:consolidate-selections (input.hidden-input)
     -0:47.2.0 core:cancel (input.hidden-input)
     -0:46.6.0 intentions:highlight (input.hidden-input)
     -0:46.3.0 command-palette:toggle (input.hidden-input)
  2x -0:43.8.0 core:move-down (input.hidden-input)
     -0:43 core:confirm (input.hidden-input)
     -0:43 markdown-themeable-pdf:export (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-shell-commands 1.5.0 
intentions 1.1.5 
livereload 0.4.4 
markdown-themeable-pdf 1.2.1 
pdf-view 0.71.0 
platformio-ide-terminal 2.9.4 
sort-lines 0.19.0 
```

**Comment by Kuurusch** [comment]
Have same issue! Used it without any customizations on a Windows 10 Machine!

**Comment by garasuT** [comment]
Same issue on Windows 10 with customized settings, but those settings went well before

**Comment by ventolinmx** [comment]
Hi, same issue here. Tried different settings of the package but same error results.

**1. Markdown to pdf.**

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Debian GNU/Linux
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1


### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Object.getConfigFilePath (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:575:28)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:365:44
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

### Commands

```
     -5:33.4.0 timecop:view (input.hidden-input)
     -3:56.1.0 find-and-replace:use-selection-as-replace-pattern (input.hidden-input)
     -3:41 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -3:34.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:46 markdown-preview:toggle (input.hidden-input)
     -2:28.6.0 find-and-replace:use-selection-as-replace-pattern (input.hidden-input)
  3x -2:18.8.0 markdown-themeable-pdf:export (div.line.cursor-line)
```

### Non-Core Packages

```
graphviz-preview 1.7.0 
linter 2.3.0 
linter-spell 0.15.0 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
pandoc-convert 1.1.1 
pdf-view 0.71.0 
split-diff 1.6.0 
```

**Comment by shine93** [comment]
same issue， how to fix

**Comment by imadcat** [comment]
same issue

**Comment by dong0hui** [comment]
I tried uninstall and reinstall another package markdown-pdf, then markdown-themeable-pdf works. Also pdf-view package is required.

**Comment by baatochan** [comment]
Got the same error on Manjaro and Windows 10 while running the export from `ctrl+shift+p` (command palette (?)). Effectively can't use the extension.

**Comment by geraertsf** [comment]
I had the same behaviour as described above. 
I have disabled all header, footer and style.css customizations. 
Close the tab settings. Close atom. 

Then when reopen atom all works.
I have the impression that there is a problem when you leave the Settings tab open when you have made changes in the package settings

**Comment by dong0hui** [comment]
> I had the same behaviour as described above.
> I have disabled all header, footer and style.css customizations.
> Close the tab settings. Close atom.
> 
> Then when reopen atom all works.
> I have the impression that there is a problem when you leave the Settings tab open when you have made changes in the package settings

I realized one need to make sure the project is opened in the folder where markdown file exists. I tried to open atom project from the folder and then the error is gone. The error is just about finding the correct path, in my view.

**Comment by aujang** [comment]
> I realized one need to make sure the project is opened in the folder where markdown file exists. I tried to open atom project from the folder and then the error is gone. The error is just about finding the correct path, in my view.

This is the correct fix. You must open the folder with Atom (and not the individual file) and then choose to convert to PDF.

**Comment by baatochan** [comment]
having to open folder in atom for this extension to work is not a fix. it is a workaround. a user should not be forced to open folder in atom for that stuff to work.

**Comment by chymian** [comment]
when will that be fixed? as said here

> having to open folder in atom for this extension to work is not a fix. it is a workaround. a user should not be forced to open folder in atom for that stuff to work.

I totally agree!

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
