### ISSUE TITLE
Latex mathematical equations integration

### ISSUE THREAD

**Issue by EpicKiwi** [cakebake/markdown-themeable-pdf#13]
It is possible to add a latex mathematical equation system like mathjax in generated pdf ?

**Comment by cakebake** [comment]
I haven't need it so far. Have you any suggestions and examples?

**Comment by cakebake** [comment]
Do you think such a thing?

https://github.com/runarberg/markdown-it-math

**Comment by dsifford** [comment]
+1 @EpicKiwi -- This feature is absolutely mandatory for anybody in academia.

@cakebake perhaps you can get in touch with @Galadirith for help with this? His Markdown-preview-plus package delivers this function really nicely.

**Comment by Galadirith** [comment]
@cakebake @dsifford I'd be really happy to lend a hand on implementing this, assuming its a feature you would be happy to integrate @cakebake.

I had opened a PR travs/markdown-pdf#88 but there's been no commits to `markdown-pdf` for over 2 months. But the point is that essentially `markdown-preview-plus` is ready to go in exporting maths to any pdf renderer.

> Do you think such a thing?  
> https://github.com/runarberg/markdown-it-math

We actually use that for our maths support. However it by default converts to mathml; I don't know how your render your pdf's but if webkit or blink is used at any point it won't work because they don't support mathml.

Please let me know your thoughts @cakebake. Thanks everyone.

**Comment by cakebake** [comment]
@Galadirith I am pleased to add new features, as long as they do not interfere with me working with the package.^^

How do you imagine an integration? `markdown-themeable-pdf` generates the HTML with [markdown-it](https://github.com/markdown-it/markdown-it) and renders this with [html-pdf](https://github.com/marcbachmann/node-html-pdf) (phantomjs/webkit). Currently I am also still looking for an alternative for clickable hyperlinks....

**Comment by bigyuki** [comment]
+1

**Comment by dpo** [comment]
MathJax would be the way to go, unless you want to use MultiMarkdown to convert to LaTeX.

**Comment by tobihagemann** [comment]
+1

**Comment by bachy** [comment]
hello and thanks for the great plugin!
i need too latex mathematical support for university
i'm using for now this atom plugin : https://github.com/shd101wyy/atom-markdown-katex
but i miss your plugin's features so much :(

**Comment by dpo** [comment]
https://atom.io/packages/markdown-preview-plus

**Comment by cakebake** [comment]
Sorry folks, but I myself know too little about the subject. If someone wants to take care of it (PR) ??

**Comment by IreneCrisologo** [comment]
+1

**Comment by cakebake** [comment]
Close this, because I know too little about the subject. If someone wants to take care of it, please let me know...

**Comment by kaslusimoes** [comment]
I am not sure how this is done (not a html/css/js person), but maybe [KaTeX](https://github.com/Khan/KaTeX) is a nice option to render LaTeX math environments?

**Comment by EpicKiwi** [comment]
This issue is closed from long time ago but this functionality could be great to implement.
I've already made a latex equation renderer to PNG with MathJax and node-canvas but it's require the installation of Cairo (a graphical library) to render the canvas to image. But, MathJax can Render to MathMl and Svg. If the renderer supports SVG, only MathJax could be used.
What do you think ?
