### ISSUE TITLE
Uncaught Error: html-pdf: Received the exit code '1'Auto configuration failed140498301443712:er...

### ISSUE THREAD

**Issue by codesnippy** [cakebake/markdown-themeable-pdf#134]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Debian GNU/Linux
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught Error: html-pdf: Received the exit code '1'
Auto configuration failed
140498301443712:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140498301443712:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140498301443712:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140498301443712:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

```
At /home/wouter/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:496

Error: html-pdf: Received the exit code '1'
Auto configuration failed
140498301443712:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140498301443712:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140498301443712:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140498301443712:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

    at ChildProcess.respond (/packages/markdown-pdf/node_modules/mdpdf/node_modules/html-pdf/lib/pdf.js:121:31)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -0:46.3.0 markdown-themeable-pdf:export (div.line)
     -0:25.1.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:11.7.0 markdown-themeable-pdf:export (div.line)
```

### Non-Core Packages

```
language-markdown 0.37.0 
markdown-pdf 2.2.0 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.11.9 
pdf-view 0.72.0 
```

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
