### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Andyszl** [cakebake/markdown-themeable-pdf#138]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at Object.getConfigFilePath (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:575:28)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:365:44
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

### Commands

```
     -0:54.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:54.9.0 snippets:expand (input.hidden-input)
     -0:54.9.0 editor:indent (input.hidden-input)
     -0:50.4.0 editor:newline (input.hidden-input)
  2x -0:45 core:backspace (input.hidden-input)
     -0:42.2.0 editor:newline (input.hidden-input)
  2x -0:41.1.0 core:move-up (input.hidden-input)
     -0:36.9.0 core:move-down (input.hidden-input)
  2x -0:36.6.0 core:move-left (input.hidden-input)
     -0:33.8.0 core:move-down (input.hidden-input)
     -0:27.3.0 markdown-themeable-pdf:export (div.highlights)
```

### Non-Core Packages

```
markdown-image-paste 2.5.2 
markdown-preview-plus 3.11.5 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.2 
markdown-themeable-pdf 1.2.1 
pdf-view 0.72.0 
```

**Comment by baatochan** [comment]
There's workoaround for it in #128. You need to open the folder as a project.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
