### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by sbarber51** [cakebake/markdown-themeable-pdf#141]
[Enter steps to reproduce:]

1. Open markdown file to convert
2. hit "ctrl+shft+E"
3. See error

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:1037:7)
    at Object.getConfigFilePath (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:575:28)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:365:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

### Commands

```
     -0:07.8.0 markdown-themeable-pdf:export (div.line)
```

### Non-Core Packages

```
markdown-themeable-pdf 1.2.1 
```

**Comment by sbarber51** [comment]
This was from a fresh install of Atom

**Comment by sbarber51** [comment]
Duplicate issue with known workarounds

**Comment by chymian** [comment]
ok, a workaround is no fix!  and which duplicate? link?
you want us to search through all issues? really?

**Comment by 12emerta** [comment]
In case anyone needs it:
There's workaround for it in #128. You need to open the folder as a project before trying to convert to PDF.

That wasn't so hard.
