### ISSUE TITLE
No PNG pictures in PDF or HTML exports

### ISSUE THREAD

**Issue by Spirit328** [cakebake/markdown-themeable-pdf#19]
Hi cakebake!
I like the idea of your plug-in "markdown-themeable-pdf". 
Unfortunately it does not include PNG pictures neither into PDF export, nor in HTML exports. This is a real pitty, because I am using these picture format all day long.
Is this a "not-yet-implemented-feature" or a "little-tiny-bug"?

Nevertheless. 
I have to write it in capital letters: COOL TOOL! +1

**Comment by cakebake** [comment]
Hi Spirit328,

nice that you like the package.

PNG images work wonderfully. See [Demo.pdf](https://github.com/cakebake/markdown-themeable-pdf/raw/master/tests/Demo.pdf) - the PDF version of [Demo.md](https://github.com/cakebake/markdown-themeable-pdf/raw/master/tests/Demo.md). (Local image page 5/6).

Possibly it is up to you on the image filename. Look at this #9 and ref Issues.
