### ISSUE TITLE
Text in generated PDF is not selectable

### ISSUE THREAD

**Issue by dmurat** [cakebake/markdown-themeable-pdf#20]
I can't select text in generated PDF. Is this deliberately, or I'm doing something wrong?

**Comment by cakebake** [comment]
This is due to the used program with which you open a PDF. The atom pdf-package does not permit it, but if you eg. with Adobe Acrobat Reader, your text is selectable. :)

**Comment by dmurat** [comment]
Actually, it is not. Opening in Adobe Acrobat Reader is one of the first things that I've tried. In addition, file is 14 megs in size, which is way to much. It looks like it is one big picture, not text.

Didn't mentioned previously, I'm using Atom on OSX.

**Comment by cakebake** [comment]
Sorry, but I'm not using OSX and can not test that. Did you accidentally exported as graphics instead of PDF? ^^ The Export definitely works with selectable text.

**Comment by cakebake** [comment]
Windows, Adobe Acrobat Reader DC 2015 Version | Version 2015.009.20077

![unbenannt](https://cloud.githubusercontent.com/assets/7462226/11240310/ead158c0-8df1-11e5-835f-96d887226c57.PNG)

**Comment by dmurat** [comment]
I've just used the command from right-click menu on markdown file.
Hmm, will try on windows and will report back.

**Comment by dmurat** [comment]
Yes, it works on Windows. Main difference between generated PDFs is that one from Windows does have embedded fonts, while one from OSX does not.

I can't debug this further, since I don't know how. If some kind of logging can be turned on, maybe that can be helpful. Again, I don't know how.

**Comment by cakebake** [comment]
I would be interested if a PDF that you have created under Windows, behaves well in OSX.

Unfortunately, I can not alter the fact anyway. :/ The Issue would have to go to phantom.js. 

https://github.com/ariya/phantomjs
