### ISSUE TITLE
Links are not converted correctly

### ISSUE THREAD

**Issue by chbiel** [cakebake/markdown-themeable-pdf#21]
I have a Link like this:
`[Google Maps Time Zone API](https://developers.google.com/maps/documentation/timezone/intro)`

The specs say this is a correct link, but the converter (to pdf) outputs the text and then the link instead.

If helpful:
I use the link within a nested list

I use version 0.10.1

**Comment by cakebake** [comment]
Sorry, but currently phantom.js (base module for printing) can not print clickable links. Once there are better options here, I am happy about proposals!!!

**Comment by chbiel** [comment]
OK sorry, you are right

For everyone searching for this: https://github.com/ariya/phantomjs/pull/13250
It is planned for 2.0.1 release of phantom.js

**Comment by ShaunDychko** [comment]
A workaround at the moment is to write `[](http://example.com)`. It will render as a clickable link, but it isn't possible to set the title text.
