### ISSUE TITLE
table header collision

### ISSUE THREAD

**Issue by diggit** [cakebake/markdown-themeable-pdf#24]
Tables over multiple pages in PDF export mode has colliding header with first row after page-break inside table.
![page-break](https://cloud.githubusercontent.com/assets/512025/12096490/ee769d2a-b315-11e5-81d3-f1b6ab94b361.png)

**Comment by cakebake** [comment]
Could you please attach the markdown text to reproduce? You can replace sensible information with nonsense text.
I know of this behaviour, let's see if I could fix it with your markdown. I have fixed it with my demos.

**Comment by diggit** [comment]
My markdown was nothing special. It looks different now, but here is example that produces this problem too. (Modified style, header and footer included too)

[example.zip](https://github.com/cakebake/markdown-themeable-pdf/files/77817/example.zip)

**Comment by cakebake** [comment]
I think this happens because of an error in phantomjs (headless browser with pdf print support).

In future, I will look for another renderer, because I'm generally not completely satisfied. Atom (electron) has build in pdf printing (like chrome), but breaks tables -.-

Anyway, this is a Major Issue at which I work. I leave the issue open, but can not help you up to date. :/

**Comment by diggit** [comment]
Yeah, you are right! https://github.com/ariya/phantomjs/issues/10927

Workaround mentioned in that bugreport: `thead, tfoot {display: table-row-group;}` makes only one `thead` but page-break looks bad too.
![page-break_2](https://cloud.githubusercontent.com/assets/512025/12129362/67ad61a4-b403-11e5-86dc-f0f6cdc9f673.png)
Table is separated, but on wrong place.

I'll stay tuned, your package pretty good!

**Comment by cakebake** [comment]
Thank´s!

Since 2012 not solved :(

I'd like to switch to another headless browser, but I would like for all operating systems have a base. With hyperlinks it's the same.

**Comment by walter-psjr** [comment]
I had the same problem and solved by replacing the blanks by `&nbsp;` the table thead. For example:

```
<table>
    <thead>
        <tr>
             <th>It&nbsp;is&nbsp;an&nbsp;example<th>
        </tr>
    </thead>
    ...
</table>
```

**Comment by cakebake** [comment]
This issue is obsolete. Since last versions of phantomjs the header is not repeated over pages anymore. Unfortunately -.- ariya/phantomjs#13193 ariya/phantomjs#12422 ariya/phantomjs#10615
