### ISSUE TITLE
make header and footer functions smarter

### ISSUE THREAD

**Issue by diggit** [cakebake/markdown-themeable-pdf#26]
It would be useful to generate footer and header for each page separately. Then footer and header functions could accept some parameters like actual page and so. 
This will allow eg.:
- header to be aligned left/right according to even/odd page for printed documents.
- skip header/footer on first page, or so
- ...

**Comment by cakebake** [comment]
Currently, I can not say whether and how it is possible to do. Also this is a matter of phantomjs. The feature is not planned from my side - sorry, but I gladly suggestions via PR.
