### ISSUE TITLE
Searchable PDF

### ISSUE THREAD

**Issue by philihub** [cakebake/markdown-themeable-pdf#29]
Hi Jens, love your package. However, I am missing the possibility to search/highlight in the PDF. Its just created as an image atm. I am on OS X 10.11.2.

Cheers,
Philip

**Comment by cakebake** [comment]
Hi philihub!

In issue #20, the same topic is covered. Unfortunately, my hands are tied. :/

**Comment by philihub** [comment]
It's a pity. A "real" PDF would greatly enhance the usability.

**Comment by cakebake** [comment]
Unfortunately, I can not say anything about Mac OS, but definitely that PDF's are generated correctly (Win / Linux). Maybe you will find something in phantom.js repository/issues?
