### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by martymcflywa** [cakebake/markdown-themeable-pdf#3]
[Enter steps to reproduce below:]
1. Open a markdown file
2. Press CTRL+SHIFT+E to export

Right clicking in markdown preview also does nothing.

**Atom Version**: 1.0.9
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.7.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\marty\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:304

TypeError: undefined is not a function
  at C:\Users\marty\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:304:20
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```
### Commands

```
     -1:01.1.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
     -0:41 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:07.3.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "projectHome": "C:\\Users\\marty\\Dropbox\\Documents\\ecu"
  },
  "markdown-themeable-pdf": {}
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.18.0
language-asp, v1.0.0
language-aspx, v0.4.0
language-latex, v0.6.1
markdown-scroll-sync, v0.4.0
markdown-themeable-pdf, v0.7.2
save-session, v0.15.7
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by cakebake** [comment]
Hey, thank´s for your report. Is that once happened, or happens to you every time? I and my colleagues also work with Windows. Here everything works. May be the package was not installed correctly. Most simply uninstalling it easy and install it again. Possibly a node module was not available on npmjs.com at the time of your installation.

The right click on markdown preview is a known issue and and is achieved up to v1.0.

**Comment by cakebake** [comment]
I close this issue. Please let me know if you have this problem again.

**Comment by nkamat-im** [comment]
I have the same issue on Ubuntu

**Comment by cakebake** [comment]
I'm testing it and add some more human friendly error messages... ;)

**Comment by martymcflywa** [comment]
Apologies for late response. I disabled [markdown-scroll-sync](https://atom.io/packages/markdown-scroll-sync) and it worked perfectly after that.

I may have also disabled [markdown-pdf](https://atom.io/packages/markdown-pdf) to get it working, although I'm not 100% sure. I've disabled it anyway since this great addon replaces it =)

**Comment by cakebake** [comment]
Ah, very good! I look at the whole still at times where the incompatibility occurs. I am pleased that now everything works :)

**Comment by pfaffman** [comment]
As @martymcflywa said, disabling markdown-pdf made this error go away. Perhaps the install could test if markdown-pdf is also installed? My first take was that they were related, not against each other.

**Comment by cakebake** [comment]
I look at this closer, when such interest exists here ;)

**Comment by cakebake** [comment]
Hmm, I tried it with following packages... Everything works with:
- markdown-format
- markdown-pdf
- markdown-scroll-sync
- markdown-themeable-pdf

I let the plugins installed in my development environment. So I will eventually notice an error, if it exists. I do not think that all reported errors here have the same cause. Please create a new Issue, if something happens.

![markdown-packages](https://cloud.githubusercontent.com/assets/7462226/9861493/f4b5eabe-5b32-11e5-8c53-8e337162ff01.png)
