### ISSUE TITLE
Really good !

### ISSUE THREAD

**Issue by mazito** [cakebake/markdown-themeable-pdf#30]
This is what I expected from a PDF converter ! I was really missing the page headers and footers in my pdfs. Now I could customize them for my docs.

I have one question: what other tags aside from {{page}} and {{pages}} can I use in the header and footer. I usually include the `doc/file name`, the `doc version` and the `date` in the footer. 

I understand how to customize the date because it was in the footer.js file, but is it posible to define and/or set those variables without touching the footer.js for every file ?  

Thanks again for an excellent package !!!

Mario

**Comment by cakebake** [comment]
Thank you for the praise. Glad you like it! :) To your question, there is already an issue #28
