### ISSUE TITLE
File links dont show well when rendered

### ISSUE THREAD

**Issue by mazito** [cakebake/markdown-themeable-pdf#31]
When inserting a file link `[ my file title ]( ./file-name.xls )`  for example it does not show well when rendered.

For example:

```
Ver el archivo **[departamentos.xls](./departamentos.xls)**
```

is rendered as:
![captura de pantalla de 2016-01-20 21 29 21](https://cloud.githubusercontent.com/assets/1116909/12467762/e8e231a4-bfbc-11e5-8c00-6ff949084ff2.png)

What I get is BOTH the link title AND the file url itself shown. Is there any solution to this ?

I tried other ways too:

```
Ver el archivo **[ departamentos ](departamentos.xls)**

Ver el archivo **[departamentos.xls](../departamentos.xls)**
```

 but they give the same result:
![captura de pantalla de 2016-01-20 21 34 35](https://cloud.githubusercontent.com/assets/1116909/12467841/a0f004ec-bfbd-11e5-9370-d63e7575b5a1.png)

Thanks !!!

Mario

**Comment by dynobo** [comment]
I have the same problem, but with all links.

`[Google](http://google.com)` 

gots rendered with Link and Title:

Google http://google.com

and the Link is not clickable. 

Also, when I enter ONLY the Link:

`http://google.com`

I got the link twice, once normal text, once blue, but again, not clickable:

http://google.com http://google.com

Tried it with activated and deactivated option "Autoconvert URL-like text to link".

**Comment by jbaksta** [comment]
I've been able to repeat this as well. You can apply a workaround I suppose by applying your own custom CSS to override the `a[href]:after` and the `a,a:visited`. However, I made the simple changes to the `css/document.css` file in prep for a PR if requested:

``` css
a,
a:visited {
    text-decoration: none;
    /*color: inherit;*/
    color: #337AB7;
}

/*
a[href]:after {
    content: " " attr(href);
    color: #337AB7;
}
*/
```

**Comment by cakebake** [comment]
Unfortunately PhantomJS produces no clickable links. The CSS hack is just a hack. This is definitely on my Todo, but my hands are currently tied.

**Comment by jbaksta** [comment]
Yes, plain hack/workaround , but at least it doesn't render the link twice in this case. I knew it wasn't clickable which wasn't what I needed right then, but I couldn't have the links doubly printed.

**Comment by cakebake** [comment]
I hope everyone gets currently clear. I cant currently do much, because PhantomJS does not support clickable links. I stay tuned ...

**Comment by leodutra** [comment]
Any update on this feature?

**Comment by cakebake** [comment]
Yes, PhantomJS was updated, now I just have to find the time to revise all once. :)

**Comment by shnbwmn** [comment]
This (big) caveat is the only thing getting in my way of using this package as my go-to MD to PDF converter. Awaiting fix patiently :bowtie:

**Comment by leodutra** [comment]
Using but awaiting... almost begging.
If I had spare time, I'd try to implement.

**Comment by shnbwmn** [comment]
[Noice](https://www.youtube.com/watch?v=usfiAsWR4qU) :+1:

**Comment by leodutra** [comment]
Ow God! YEEES!
