### ISSUE TITLE
monospace font for code

### ISSUE THREAD

**Issue by bachy** [cakebake/markdown-themeable-pdf#33]
Hello and thanks for this great module
I have one issue really important for me, code blocks are not rendering into monospaced font in pdf export.
it's working for preview but not for pdf export, is it a bug just for me ? how can i try to fix that ?

thanks

**Comment by cakebake** [comment]
Do you have an example (All files, md+html+pdf) of me? Of course you can edit the CSS and assign an individual font for HTML tag `code` and `pre`.

Doc: https://github.com/cakebake/markdown-themeable-pdf#custom-css
