### ISSUE TITLE
styles.css project specific ignored

### ISSUE THREAD

**Issue by yoghi** [cakebake/markdown-themeable-pdf#38]
My obiective is create a custom styles.css for my markdown book project. 
1) I have create the directory markdown-themeable-pdf
2) generated a styles.css into markdown-themeable-pdf dir 
3) generate pdf (ctrl-shif-e)

But the generated pdf haven't any of my custom

OS: Macosx 10.9.5
Atom: 1.5.4

**Comment by cakebake** [comment]
Works on windows and linux. I have no mac and could not test it :/

The atom project must have the structure

```
--- project
- markdown-themeable-pdf/
--- footer.js
--- header.js
--- ...
- somedir/
- document.md
- somefile.js
- ...
```

Hope that helps! If you have modified your path to the custom css file in plugin settings, please name your folder like defined in your configuration.
