### ISSUE TITLE
Allow changes in header.js / footer.js without restarting atom

### ISSUE THREAD

**Issue by schwaerz** [cakebake/markdown-themeable-pdf#39]
Is it possible to somehow allow to change header & footer without the need to restart atom?

BTW.: Is there a way to include some document title or current level-1 header (h1) on each page's header?

**Comment by cakebake** [comment]
Currently I have no idea how I could do it without lothing other advantages. Atom loads node modules (header and footer are) after a reload. You could reload your editor instead of restart.

You can write HTML in header and footer. Maybee wathing this issue #28 is also relevant.
