### ISSUE TITLE
Nothing happens neither when right-clicking nor when using Ctrl-Shift-E

### ISSUE THREAD

**Issue by FrancoisEx** [cakebake/markdown-themeable-pdf#4]
I just installed the package in Atom, very seduced by the possibility to edit texts in Markdown formats. Nothing happens ... I use Atom version 1.0.10 on Mac OS X 10.10.5.

What should I do to get it working?

Best Regards,

**Comment by cakebake** [comment]
Sorry, but I couldn't test it on a Mac... What says your error console in development view?

**Comment by cakebake** [comment]
Ok, for Mac the keyboard shortcuts are missing. These come in the next patch release.

**Comment by cakebake** [comment]
Are there Mac users who use the package?! I need testers with a relatively short response time ^^

**Comment by c-baillie** [comment]
Sure! Looks like a great package. Couldn't get it to work on mac.

**Comment by cakebake** [comment]
@c-baillie Have you Javascript skills to find out where the problem lies?

**Comment by c-baillie** [comment]
Sorry! Know almost nothing. Rush of blood to the head. May not be that
useful.
I have some free time in two weeks and I'll look at the code then if useful.

Charles

**Comment by jslvtr** [comment]
Not sure if this has been solved, but my Mac shortcuts work.

**Comment by cakebake** [comment]
Thank you for reporting :)
