### ISSUE TITLE
Bullet formatting - markdown taken from GitLab

### ISSUE THREAD

**Issue by mhGLEIF** [cakebake/markdown-themeable-pdf#42]
Hello there,

I noticed that some bullet point levels are missing when I create a PDF with this package.

The source MD comes from Atom and has been optimized to render in GitLab's editor (which has some known quirks with bullet points).

Is there a recommendation on syntax to make bullets "just work" in a minimal way with markdown-themeable-pdf?

**Comment by cakebake** [comment]
Have you any examples?

```
-   One
-   Two
    -   One
    -   Two
        -   One
        -   Two
        -   Three
    -   Three
-   Three
-   Four
```

**Comment by cakebake** [comment]
If you have any problems, let me know.
