### ISSUE TITLE
Suggestion: diffrent first page

### ISSUE THREAD

**Issue by sheggi** [cakebake/markdown-themeable-pdf#43]
It would be cool to enable a first page with different styling from the rest of the document.

**Comment by cakebake** [comment]
You could write html on the first page with an wrapper class for your styles.

``` html
<div class="my-style-for-this-page">
<h1>Heading</h1>
<p>Lorem ipsum dolor sit amet</p>
</div>
<div class="page-break"></div>
```

I don´t think that other technical options are not available.
