### ISSUE TITLE
image not showing up in pdf

### ISSUE THREAD

**Issue by rduvoisin** [cakebake/markdown-themeable-pdf#45]
I insert an image in md.

`![](serious/roc.png)`   

(No embedded spaces in the filename.)

It doesn't show up in the pdf. (It does show up in "markdown-preview" and It does work with "markdown-pdf" plugin.)

**Comment by cakebake** [comment]
duplicate of #41

**Comment by IreneCrisologo** [comment]
@rduvoisin try `![](./serious/roc.png)` instead
