### ISSUE TITLE
html tags disables markdown formatting

### ISSUE THREAD

**Issue by IreneCrisologo** [cakebake/markdown-themeable-pdf#47]
Hi!

When I try to convert a markdown that uses html tags to format some lines (centering them for example) it ignores the markdown formatting and just considers everything inside as regular text.
Kindly see below some code example and the output.

Code:
![image](https://cloud.githubusercontent.com/assets/4422950/15510482/c5758162-21d7-11e6-86c7-2a82e86db8f5.png)

PDF:
![image](https://cloud.githubusercontent.com/assets/4422950/15510485/cd3763fc-21d7-11e6-84ea-d0fc879951df.png)

I've tried searching for other ways to center lines but using html tags is what everyone recommends. Can this be integrated in the package? :)

Cheers,
irene

**Comment by cakebake** [comment]
Sorry, but inside html you must work with pure html only :( This is because of limitation by `markdown-it` module.

**Comment by cakebake** [comment]
@irenemeanspeace coul this help you out? maybe I could implement it, if it make sense.

https://www.npmjs.com/package/markdown-it-container
