### ISSUE TITLE
Ancor link not rendered

### ISSUE THREAD

**Issue by noraj** [cakebake/markdown-themeable-pdf#48]
Ancor link (link to title for example) like those generated with TOC are not rendered.

Ex : `[But](#but)`

Just for info [markdown-pdf](https://github.com/travs/markdown-pdf) does it well if you want to check their code.

**Comment by cakebake** [comment]
This is an html-pdf issue marcbachmann/node-html-pdf#113

I hope they could fix it. I have added an parser extension to add id´s to headings without TOC.

![bildschirmfoto vom 2016-06-26 15-36-24](https://cloud.githubusercontent.com/assets/7462226/16362604/cdc62970-3bb3-11e6-949e-9b3251be31c8.png)
