### ISSUE TITLE
Reference local images within header and footer

### ISSUE THREAD

**Issue by enjoylife** [cakebake/markdown-themeable-pdf#5]
Only see the TODO message in the docs. Is there any status on this feature?

**Comment by cakebake** [comment]
It is planned for the near future. One of the next steps for 1.0 :) I put this issue on closed, when it works. In the meantime, you can use absolute paths?

**Comment by arnekolja** [comment]
Absolute paths don't work.

```
module.exports = function () {
    return {
        height: '2cm',
        contents: '<div style="text-align: center;"><span><img src="/Users/arne/.atom/markdown-themeable-pdf/logo.jpg" /></span></div>'
    };
};
```

gives just a blank header, no matter if I give an PNG or JPG. The path is definitely correct.

edit: CSS images don't work, either.

**Comment by cakebake** [comment]
New status: I need this feature in any case this week for a manual for one of our products, too ;)

@arnekolja Paths should be start with `file:///`.

Why base64 encoded pictures as img-src do not work is still a mystery.
