### ISSUE TITLE
Add #include "path to an other md file"

### ISSUE THREAD

**Issue by gouz** [cakebake/markdown-themeable-pdf#50]
It will be awesome to include some markdown file into another one.
Big feature for long document like books, ...

**Comment by cakebake** [comment]
Sorry, but that's not on my plan.

**Comment by cakebake** [comment]
I will test this https://www.npmjs.com/package/markdown-it-include

**Comment by cakebake** [comment]
Sorry, plugin throws error `Uncaught (in promise) Error: ENOENT: no such file or directory` and could not resolve the file path correctly...

If anyone knows alternatives - please let me know.
