### ISSUE TITLE
Feature Request: generate pdf menu base on markdown title

### ISSUE THREAD

**Issue by ybak** [cakebake/markdown-themeable-pdf#57]
Thanks for your great work.
It would be better if the generated pdf includes menu base on markdown title.
like:

```
# h1
## h2
# h1'
## h2'
### h3'
```

 will generate pdf menu:

```
h1
--h2
h1'
--h2'
----h3
```

Thanks.

**Comment by cakebake** [comment]
I think - duplicate of #65
