### ISSUE TITLE
Text too small

### ISSUE THREAD

**Issue by technopig** [cakebake/markdown-themeable-pdf#62]
When exporting a markdown page to pdf, the text comes out very small. Small enough that if the PDF is printed, the text is barely legible.

Suggested ideal fix: make the PDF output have the same font size as the original MD file.

**Comment by nateGeorge** [comment]
+1

**Comment by nateGeorge** [comment]
You can change it in the .css file for markdown-themable-pdf.  Mine was `C:\Users\ngeorge\.atom\markdown-themeable-pdf\style.css`, although that's in Windows.  In the settings it has a clue to the relative path for your system.

**Comment by M-Fabian** [comment]
Can you please give an example on how to do this? I want to increase the overall font includung code, headers, lists and normal text.

**Comment by M-Fabian** [comment]
This is how I did it, which works for me. I only listed h1. h2-h6 can be adjusted similarly.
```
html, body, code, pre code {
    font-size: 14px;
}

h1 {
    font-size: 36px;
}
```

Nevertheless, the default of 10px is too small IMHO.
