### ISSUE TITLE
Apparently header/footer is not rendered when exported to HTMl

### ISSUE THREAD

**Issue by ovizii** [cakebake/markdown-themeable-pdf#68]
which makes it really hard to customize my header and footer. 

To give you an example: 
I manually inserted a table into my footer with 3 columns and it would be so much easier to style if I could export it to html then open it in a browser and analyse the source code.

Could this be made possible?

**Comment by cakebake** [comment]
You could change package settings to your needs.

![bildschirmfoto vom 2017-04-09 21-22-07](https://cloud.githubusercontent.com/assets/7462226/24840275/9ab855f0-1d6a-11e7-96c8-f43edf7ba1c6.png)

**Comment by mdrx-io** [comment]
@cakebake even when changing the package settings to export as HTML, the resulting HTML file does not include the header element(s). Were you suggesting to modify the package to add a setting for this?
