### ISSUE TITLE
Support less files

### ISSUE THREAD

**Issue by jledruide** [cakebake/markdown-themeable-pdf#73]
Is it possible add the intégration of "less" files in addition to css custom style path ?

For example, it will be easier to import other common styles files.

In my case, I try to have common styles between the preview of the MD files and the result of the PDF export.

In the same way, adding a specific ID or CLASS after the <body> would make the distinction (like for class .markdown-preview).

**Comment by cakebake** [comment]
You need to precompile the CSS. I would not see the task in this plugin - sorry. Maybe gulp or a less package for atom is a help?

**Comment by jledruide** [comment]
Good idea, I will search in this way. Thanks.
