### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by MarcuSacramento** [cakebake/markdown-themeable-pdf#87]
It would be interesting that using [emojis as in github](https://help.github.com/articles/basic-writing-and-formatting-syntax/#using-emoji) would also be rendered in the output file 

Examples:

Writes on .md file:
```:arrow_heading_up: :+1: :bulb:```

Output on PDF or HTML file:

:arrow_heading_up: :+1: :bulb:

**Comment by tatoosh** [comment]
This would help me, too.

**Comment by tatoosh** [comment]
Plesse close, duplicate to #54.
