### ISSUE TITLE
Stopped working, how do I debug?

### ISSUE THREAD

**Issue by ovizii** [cakebake/markdown-themeable-pdf#89]
As usual I press: CTRL+SHIFT+E - I see the usual notification saying: start converting myfile.md then nothing happens. A myfile.pdf gets created with a size of 0.

What to do now?

**Comment by cakebake** [comment]
Hi ovizii,

i would suggest to completely reinstall the package in your atom editor. I could not reproduce your problem. If that doesn´t work, please write a new issue to get the problem.
