### ISSUE TITLE
image not showing up in pdf.

### ISSUE THREAD

**Issue by sander76** [cakebake/markdown-themeable-pdf#9]
I insert an image in md.

```
![](screendumpd/normally closed.png)
```

It doesn't show up in the pdf. (It does show up in "markdown-preview" and It does work with "markdown-pdf" plugin.)

**Comment by cakebake** [comment]
Yes you are right. Because of the whitespace the path could not be resolved... Please use image naming like `![](screendumpd/normallyClosed.png)`, i will fix this soon. :)
