### ISSUE TITLE
Enhancement request: menu to generate PDF/HTML/Image

### ISSUE THREAD

**Issue by lucasvieites** [cakebake/markdown-themeable-pdf#93]
Hi,
I'd like to be able to generate a PDF or HTML or Image without having to change the option in the package settings. This could be in the form of a submenu of the context menu.

Thank you for the wonderful product.

Lucas Vieites

**Comment by cakebake** [comment]
Hi lucasvieites,

I´m sorry, but a menu isn´t on my plan. You could leave the settings tab open and have already a "menu".
