### ISSUE TITLE
Bookmark Support

### ISSUE THREAD

**Issue by scottix** [cakebake/markdown-themeable-pdf#98]
Any chance you will add bookmark support. That is one thing will put this converter over the top of others. I tried pandoc but it messes up too much stuff to be use-able.

**Comment by cakebake** [comment]
Hey scottix,

what do you mean with "bookmark support"?

**Comment by scottix** [comment]
Take a word document for example.

Set Header 1 Header 2 and Header 3

When you export as PDF you have an option to export Bookmarks and what this does is create a list of headers you can jump to in the document.

So if you have like a 100 page document you can find the spot you need faster.

![selection_670](https://user-images.githubusercontent.com/435727/36556925-a386ce68-17bb-11e8-9e9b-bde7364229ac.jpg)

**Comment by cakebake** [comment]
Ok, I'll take a look.

**Comment by cakebake** [comment]
The PDF is created with Chromium and unfortunately Chromium does not support bookmarks.

However, the new version will provide a way to output a table of contents #65
